#define PWDN_GPIO_NUM    -1
#define RESET_GPIO_NUM   20
#define XCLK_GPIO_NUM    42
#define SIOD_GPIO_NUM    6
#define SIOC_GPIO_NUM    7
#define Y9_GPIO_NUM      45
#define Y8_GPIO_NUM      38
#define Y7_GPIO_NUM      48
#define Y6_GPIO_NUM      39
#define Y5_GPIO_NUM      47
#define Y4_GPIO_NUM      40
#define Y3_GPIO_NUM      21
#define Y2_GPIO_NUM      41
#define VSYNC_GPIO_NUM   46
#define HREF_GPIO_NUM    44
#define PCLK_GPIO_NUM    15